Incorporate cli behaviour in the capella base image
DSD-DBS/capella-dockerimages pull request #152
Opened 2023-06-06 08:56 UTC by amolenaar

See #146.

2023-06-12 12:34 UTC, MoritzWeber0 commented on docs/docs/capella/cli.md
It doesn't make sense to have two documentation pages or `capella/base`. Please move the docs to the `capella/base` documentation page. Additionally, add a deprecation note and point to the `capella/base` documentation.

2023-06-12 12:34 UTC, MoritzWeber0 commented on docs/docs/capella/cli.md
The `docs/index.md` still contains references to `capella/cli`. Please remove them.

2023-06-12 12:35 UTC, MoritzWeber0 commented
Please use conventional commits and run `pre-commit install` to activate the `pre-commit` hooks.

2023-06-12 12:47 UTC, amolenaar commented
updated docs and commit messages.

2023-06-16 08:09 UTC, MoritzWeber0 commented on docs/docs/capella/base.md
> +    The functionalirt for running capella as a commanline app used to be part of
```suggestion
    The functionality for running capella as a command-line app used to be part of
```

2023-06-16 08:13 UTC, MoritzWeber0 requested changes
I still see one left-over of `capella/cli` in the mermaid graph of the `index.md`. Otherwise, it looks good.

2023-06-20 13:16 UTC, amolenaar commented
> I still see one left-over of `capella/cli` in the mermaid graph of the `index.md`. Otherwise, it looks good.

I considered we should leave it in, so search engines can still land on that page. 404's are bad for site score.

2023-06-20 14:06 UTC, MoritzWeber0 commented
> > I still see one left-over of `capella/cli` in the mermaid graph of the `index.md`. Otherwise, it looks good.
> 
> I considered we should leave it in, so search engines can still land on that page. 404's are bad for site score.

I'm just referring to the mermaid graph, not the page. The removal in the mermaid graph should not lead to 404's.

2023-06-22 06:41 UTC, amolenaar commented
> I'm just referring to the mermaid graph, not the page. The removal in the mermaid graph should not lead to 404's.

Fixed.

2023-06-22 06:58 UTC, MoritzWeber0 approved these changes

2023-06-22 06:59 UTC, merged