t4c/client/remote repositories across multiple instances
DSD-DBS/capella-dockerimages pull request #54
Opened 2022-10-28 12:45 UTC by TimoBbz

Adds the support of repositories across multiple instances on `t4c/client/remote` docker image, with the environment variable `T4C_JSON`.
See updated doc for more information.

2022-10-31 11:04 UTC, MoritzWeber0 requested changes
Tested it, works good on my side.

2022-10-31 13:02 UTC, TimoBbz commented on remote/setup_workspace.py
>  # SPDX-FileCopyrightText: Copyright DB Netz AG and the capella-collab-manager contributors
Do you prefer to have separate targets (`run/t4c/client/remote/repositories` and `run/t4c/client/remote/json` for example) or to have the current target overwritten?

2022-10-31 14:30 UTC, MoritzWeber0 commented on remote/setup_workspace.py
> +                rf"tcp\://{repo['host']}\:{repo['port']}/{repo['repository']}",
This line is the same for both parts. I'd pass `t4c_host`, `t4c_port` and `repo` to the function.

2022-10-31 14:32 UTC, MoritzWeber0 commented on remote/setup_workspace.py
> +def replace_config_repositories(key: str, value: str) -> None:
```suggestion
def inject_t4c_connection_details(name: str, value: str) -> None:
```

I'd choose another name here (describing what the function does). It's not really clear from `key` what it is about. And I'd replace `value`, see the comment below.

2022-10-31 15:14 UTC, MoritzWeber0 commented on remote/setup_workspace.py
>  # SPDX-FileCopyrightText: Copyright DB Netz AG and the capella-collab-manager contributors
Looks good. But I'd use `run-t4c/client/remote-legacy` and `run-t4c/client/remote-json`. This makes it consistent with the changes of #52.

2022-11-02 15:07 UTC, TimoBbz commented on remote/setup_workspace.py
>  # SPDX-FileCopyrightText: Copyright DB Netz AG and the capella-collab-manager contributors
Done.

2022-11-08 09:11 UTC, MoritzWeber0 requested changes
I'm not able to run the pytest due to a version conflict, I'll try again when support for multiple versions is merged.

2022-11-08 13:46 UTC, MoritzWeber0 approved these changes

2022-11-08 13:46 UTC, merged